apiVersion: apps/v1
kind: Deployment
metadata:
  name: "terraform-example"
  labels:
    test: "MyExampleApp"
spec:
  replicas: 3
  selector:
    matchLabels:
      test: "MyExampleApp"
  template:
    metadata:
      labels:
        test: "MyExampleApp"
    spec:
      serviceAccountName: "my-service-account"
      containers:
        - name: "example"
          image: "892893225782.dkr.ecr.us-west-2.amazonaws.com/housing-api:{{ .Values.commit }}"
          command: ["gunicorn" , "--bind",  "0.0.0.0:5000" , "app:app"]
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
