apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: housing-api-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: housing-api-service-loadbalancer
                port:
                  number: 80