version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app --reload
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - DB_URL=postgres://postgrs:postgres@db:5432/default

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local