version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app --reload -t 80
    volumes:
      - ./:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/default
      - GOOGLE_CLIENT_ID=1039455511015-9of84all5bi5apuinop5nb02udkr02ad.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local