version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 app:app --reload -t 80
    volumes:
      - ./:/usr/src/app
    expose:
      - 5000
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/default
      - GOOGLE_CLIENT_ID=1039455511015-9of84all5bi5apuinop5nb02udkr02ad.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - SECRET_KEY=secret
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '5555:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  alembic:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/default
    depends_on:
      - db

  nginx:
    build: ./nginx/dev
    ports:
      - 80:80
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
